import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';
import '../../../features/event/models/reminder_model.dart';
import '../../../utils/exceptions/firebase_exceptions.dart';
import '../../../utils/exceptions/format_exceptions.dart';
import '../../../utils/exceptions/platform_exceptions.dart';

class ReminderRepository extends GetxController {
  static ReminderRepository get instance => Get.find();

  final _db = FirebaseFirestore.instance;
  CollectionReference get _remindersCollection => _db.collection('reminders');

  /// Create a new reminder (使用 Firestore 自动生成 ID)
  Future<String> createReminder(Reminder reminder) async {
    try {
      final docRef = await _remindersCollection.add(reminder.toFirestore());
      return docRef.id;
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } on FormatException catch (_) {
      throw const FFormatException();
    } on FPlatformException catch (e) {
      throw FPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// 🆕 Create 3 default reminders for event registration
  /// Returns list of created reminder IDs
  Future<List<String>> createDefaultReminders({
    required String registrationId,
    required String eventTitle,
    required DateTime eventStartDateTime,
  }) async {
    try {
      print('📝 Creating 3 default reminders for registration: $registrationId');

      final reminderIds = <String>[];

      // Reminder 1: 1 day before event
      final oneDayBefore = eventStartDateTime.subtract(const Duration(days: 1));
      final reminder1 = Reminder(
        reminderId: '', // Will be generated by Firestore
        registrationId: registrationId,
        title: 'Event Tomorrow',
        message: 'Reminder: "$eventTitle" is starting tomorrow at ${_formatTime(eventStartDateTime)}',
        remindAt: Timestamp.fromDate(oneDayBefore.toUtc()),
        createdAt: Timestamp.now(),
        isSent: false,
      );
      final id1 = await createReminder(reminder1);
      reminderIds.add(id1);
      print('   ✅ Created reminder 1 (1 day before): $id1');

      // Reminder 2: 1 hour before event
      final oneHourBefore = eventStartDateTime.subtract(const Duration(hours: 1));
      final reminder2 = Reminder(
        reminderId: '',
        registrationId: registrationId,
        title: 'Event Starting Soon',
        message: 'Reminder: "$eventTitle" is starting in 1 hour at ${_formatTime(eventStartDateTime)}',
        remindAt: Timestamp.fromDate(oneHourBefore.toUtc()),
        createdAt: Timestamp.now(),
        isSent: false,
      );
      final id2 = await createReminder(reminder2);
      reminderIds.add(id2);
      print('   ✅ Created reminder 2 (1 hour before): $id2');

      // Reminder 3: 15 minutes before event
      final fifteenMinsBefore = eventStartDateTime.subtract(const Duration(minutes: 15));
      final reminder3 = Reminder(
        reminderId: '',
        registrationId: registrationId,
        title: 'Event Starting Now',
        message: 'Reminder: "$eventTitle" is starting in 15 minutes!',
        remindAt: Timestamp.fromDate(fifteenMinsBefore.toUtc()),
        createdAt: Timestamp.now(),
        isSent: false,
      );
      final id3 = await createReminder(reminder3);
      reminderIds.add(id3);
      print('   ✅ Created reminder 3 (15 mins before): $id3');

      print('✅ Created ${reminderIds.length} reminders for registration $registrationId');
      return reminderIds;
    } catch (e) {
      print('❌ Error creating default reminders: $e');
      rethrow;
    }
  }

  /// 🆕 Delete all reminders for a registration
  Future<void> deleteAllRemindersByRegistration(String registrationId) async {
    try {
      print('🗑️ Deleting all reminders for registration: $registrationId');

      final querySnapshot = await _remindersCollection
          .where('registrationId', isEqualTo: registrationId)
          .get();

      if (querySnapshot.docs.isEmpty) {
        print('   ℹ️ No reminders found for registration $registrationId');
        return;
      }

      // Batch delete for better performance
      final batch = _db.batch();
      for (final doc in querySnapshot.docs) {
        batch.delete(doc.reference);
      }
      await batch.commit();

      print('   ✅ Deleted ${querySnapshot.docs.length} reminders for registration $registrationId');
    } on FirebaseException catch (e) {
      print('   ❌ Firebase error: ${e.code} - ${e.message}');
      throw FFirebaseException(e.code).message;
    } catch (e) {
      print('   ❌ Error: $e');
      throw 'Failed to delete reminders: $e';
    }
  }

  /// 🆕 Check if reminders exist for a registration
  Future<bool> hasReminders(String registrationId) async {
    try {
      final querySnapshot = await _remindersCollection
          .where('registrationId', isEqualTo: registrationId)
          .limit(1)
          .get();

      return querySnapshot.docs.isNotEmpty;
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// 🆕 Get all reminders for a registration (for debugging/display)
  Future<List<Reminder>> getRemindersByRegistration(String registrationId) async {
    try {
      final querySnapshot = await _remindersCollection
          .where('registrationId', isEqualTo: registrationId)
          .orderBy('remindAt', descending: false)
          .get();

      return querySnapshot.docs
          .map((doc) => Reminder.fromSnapshot(doc as DocumentSnapshot<Map<String, dynamic>>))
          .toList();
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// 🆕 Stream to check if reminders are enabled for registration
  Stream<bool> areRemindersEnabled(String registrationId) {
    try {
      return _remindersCollection
          .where('registrationId', isEqualTo: registrationId)
          .limit(1)
          .snapshots()
          .map((snapshot) => snapshot.docs.isNotEmpty);
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// Helper method to format time
  String _formatTime(DateTime dateTime) {
    final hour = dateTime.hour.toString().padLeft(2, '0');
    final minute = dateTime.minute.toString().padLeft(2, '0');
    return '$hour:$minute';
  }

  /// Delete reminder by ID
  Future<void> deleteReminder(String reminderId) async {
    try {
      await _remindersCollection.doc(reminderId).delete();
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } on FormatException catch (_) {
      throw const FFormatException();
    } on FPlatformException catch (e) {
      throw FPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// Get reminder by registration ID (returns first one)
  Future<Reminder?> getReminderByRegistration(String registrationId) async {
    try {
      final querySnapshot = await _remindersCollection
          .where('registrationId', isEqualTo: registrationId)
          .limit(1)
          .get();

      if (querySnapshot.docs.isNotEmpty) {
        final doc = querySnapshot.docs.first;
        return Reminder.fromSnapshot(doc as DocumentSnapshot<Map<String, dynamic>>);
      }

      return null;
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } on FormatException catch (_) {
      throw const FFormatException();
    } on FPlatformException catch (e) {
      throw FPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// Check if reminder exists for registration
  Future<bool> checkReminderExists(String registrationId) async {
    try {
      final reminder = await getReminderByRegistration(registrationId);
      return reminder != null;
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } on FormatException catch (_) {
      throw const FFormatException();
    } on FPlatformException catch (e) {
      throw FPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// Update reminder sent status
  Future<void> updateReminderSentStatus(String reminderId, bool isSent) async {
    try {
      await _remindersCollection.doc(reminderId).update({
        'isSent': isSent,
      });
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } on FormatException catch (_) {
      throw const FFormatException();
    } on FPlatformException catch (e) {
      throw FPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }

  /// Get reminders that are due to be sent (使用 UTC 时间比较)
  Stream<List<Reminder>> getDueRemindersStream() {
    try {
      final now = Timestamp.now();
      return _remindersCollection
          .where('isSent', isEqualTo: false)
          .where('remindAt', isLessThanOrEqualTo: now)
          .snapshots()
          .map((snapshot) {
        final reminders = <Reminder>[];
        for (final doc in snapshot.docs) {
          try {
            reminders.add(Reminder.fromSnapshot(doc as DocumentSnapshot<Map<String, dynamic>>));
          } catch (e) {
            continue;
          }
        }
        return reminders;
      });
    } on FirebaseException catch (e) {
      throw FFirebaseException(e.code).message;
    } on FormatException catch (_) {
      throw const FFormatException();
    } on FPlatformException catch (e) {
      throw FPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong. Please try again.';
    }
  }
}
