// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4V19mjJUKfwhj8bxYju8NCWsIyiXhE5E',
    appId: '1:662461658567:web:5a9f6e94a307f67c9d55e2',
    messagingSenderId: '662461658567',
    projectId: 'fir-82ffd',
    authDomain: 'fir-82ffd.firebaseapp.com',
    storageBucket: 'fir-82ffd.firebasestorage.app',
    measurementId: 'G-3P1MWJQT1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpedRolbbdSUqkBRQ7fE2WCWaUvYvvsRQ',
    appId: '1:662461658567:android:59135a22c84c61419d55e2',
    messagingSenderId: '662461658567',
    projectId: 'fir-82ffd',
    storageBucket: 'fir-82ffd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxsVDEzxvnQZxS6EhHKAJE6rN7qZiScVw',
    appId: '1:662461658567:ios:440a462be11dd87d9d55e2',
    messagingSenderId: '662461658567',
    projectId: 'fir-82ffd',
    storageBucket: 'fir-82ffd.firebasestorage.app',
    androidClientId: '662461658567-e4vv59329rlp57jcg3naoksumc309ppl.apps.googleusercontent.com',
    iosClientId: '662461658567-sbjiiec3nlov2somspfqf851bi6caj8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxsVDEzxvnQZxS6EhHKAJE6rN7qZiScVw',
    appId: '1:662461658567:ios:440a462be11dd87d9d55e2',
    messagingSenderId: '662461658567',
    projectId: 'fir-82ffd',
    storageBucket: 'fir-82ffd.firebasestorage.app',
    androidClientId: '662461658567-e4vv59329rlp57jcg3naoksumc309ppl.apps.googleusercontent.com',
    iosClientId: '662461658567-sbjiiec3nlov2somspfqf851bi6caj8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4V19mjJUKfwhj8bxYju8NCWsIyiXhE5E',
    appId: '1:662461658567:web:61402c8ac8083ffc9d55e2',
    messagingSenderId: '662461658567',
    projectId: 'fir-82ffd',
    authDomain: 'fir-82ffd.firebaseapp.com',
    storageBucket: 'fir-82ffd.firebasestorage.app',
    measurementId: 'G-9MWR6YSK2W',
  );

}